# Generated by Django 4.1 on 2022-08-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
